controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product: 
    path: /product 
    controller: App\Controller\ProductController::list 